function createfigure(x, t)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 28-Mar-2011 18:13:04

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

lgnd = ['x = index = ' num2str(t)];
Y1 = x(t, :)./max(x(t, :));

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([159.5 321.6]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([-0.001462 0.9839]);
box('on');
hold('all');

% Create plot
plot(Y1,'Parent',axes1,'DisplayName',lgnd);

% Create xlabel
xlabel({'scan number'});

% Create ylabel
ylabel({'normalised ion current'});

% Create legend
legend(axes1,'show');

